version: '2.4'
services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile.chatbot
      ssh:
        - default=${SSH_AUTH_SOCK:-/tmp/ssh_agent.sock}
    restart: unless-stopped
    ports:
      - "8001:8001"
      - "9100:9100"
    environment:
      ALLOWED_HOSTS: "*"
      NVIDIA_VISIBLE_DEVICES: all
      CUDA_VISIBLE_DEVICES: 0
    devices:
      - /dev/nvidia0:/dev/nvidia0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/chat/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - chatbot_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /var/www/static:/var/www/static:ro  # Changed to use host path
    depends_on:
      chatbot:
        condition: service_healthy
    networks:
      - chatbot_network

networks:
  chatbot_network:
    driver: bridge