global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack-notifier'

receivers:
  - name: 'slack-notifier'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#all-cloudega-test-alerts'
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'










