global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'cloudega.alertmanager@gmail.com'
  smtp_auth_username: "cloudega.alertmanager@gmail.com"
  smtp_auth_password: "icqlbopubfbxxgcs"
  smtp_require_tls: true

route:
  receiver: 'email-team'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'email-team'
  email_configs:
  - to: 'cgordon.dev@gmail.com'
    send_resolved: true